poe_stash/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user.urls")),
]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.charactersAndTabs, name="character-list-and-tabs"),
    path("api/character_detail/", views.characterDetail, name="charcter-detail"),
    path("api/stashtab/", views.stashTab, name="stash-tab"),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms


class SelectCharacter(forms.Form):
    character = forms.ChoiceField(
        widget=forms.Select(attrs={"onchange": "this.form.submit();"}), choices=[]
    )

    def __init__(self, names=None, *args, **kwargs):
        super(SelectCharacter, self).__init__(*args, **kwargs)

        if names:
            self.fields["character"].choices = [(x, x) for x in names]


# class SelectCharacter(forms.Form):
#     def __init__(self, names, *args, **kwargs):
#         options =
#         super(SelectCharacter, self).__init__(*args, **kwargs)
#         self.fields['names'] = forms.ChoiceField(widget=forms.Select(attrs={'onchange': 'this.form.submit();'}), choices)

user/views.py
import json
import os
from collections import Counter
from urllib.parse import parse_qs, urlparse

import requests
from decouple import config
from django.http import JsonResponse
from django.shortcuts import render

headers = {"User-Agent": "Mozilla/5.0 "}

cookies = {"POESESSID": config("POESESSID")}


def amendSentence(string):
    string = list(string)
    newstring = ""
    # Traverse the string
    for i in range(len(string)):

        # Convert to lowercase if its
        # an uppercase character
        if string[i] >= "A" and string[i] <= "Z":
            string[i] = chr(ord(string[i]) + 32)

            # Print - before it
            # if its an uppercase character
            if i != 0:
                newstring += "-"

            # Print the character
            newstring += string[i]

        # if lowercase character
        # then just print
        else:
            newstring += string[i]

    return newstring


def getAllData(request):

    Currency_url = (
        f"https://poe.ninja/api/data/currencyoverview?league=Standard&type=Currency"
    )
    Fragment_url = (
        f"https://poe.ninja/api/data/currencyoverview?league=Standard&type=Fragment"
    )
    Oils_url = f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Oil"
    Incubators_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Incubator"
    )
    Scarabs_url = f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Scarab"
    Fossils_url = f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Fossil"
    Resonators_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Resonator"
    )
    Essence_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Essence"
    )
    DivinationCards_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=DivinationCard"
    )
    Prophecies_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Prophecy"
    )
    SkillGems_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=SkillGem"
    )
    BaseTypes_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=BaseType"
    )
    UniqueMaps_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueMap"
    )
    Maps_url = f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Map"
    UniqueJewels_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueJewel"
    )
    UniqueFlasks_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueFlask"
    )
    UniqueWeapons_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueWeapon"
    )
    UniqueArmours_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueArmour"
    )
    UniqueAccessories_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueAccessory"
    )
    Beasts_url = f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Beast"
    Invitations_utl = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Invitation"
    )
    DeliriumOrb_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=DeliriumOrb"
    )
    Watchstone_url = (
        f"https://poe.ninja/api/data/itemoverview?league=Standard&type=Watchstone"
    )

    currencyUrl_list = [Currency_url, Fragment_url]

    itemsUrl_list = [
        Oils_url,
        Incubators_url,
        Scarabs_url,
        Fossils_url,
        Resonators_url,
        Essence_url,
        DivinationCards_url,
        Prophecies_url,
        SkillGems_url,
        UniqueMaps_url,
        Maps_url,
        UniqueJewels_url,
        UniqueFlasks_url,
        UniqueWeapons_url,
        UniqueArmours_url,
        UniqueAccessories_url,
        Beasts_url,
        Invitations_utl,
        DeliriumOrb_url,
        Watchstone_url,
    ]

    poeNinjaData = []

    for idx, url in enumerate(currencyUrl_list):
        qs = urlparse(url)

        if parse_qs(qs.query)["type"][0] != "Currency":
            ninjaType = amendSentence(parse_qs(qs.query)["type"][0]) + "s"
        else:
            ninjaType = amendSentence(parse_qs(qs.query)["type"][0])

        r = requests.get(url)
        result = r.json()

        items = [
            {
                "baseType": item["currencyTypeName"],
                "detailsId": item["detailsId"],
                "ninjaType": ninjaType,
            }
            for item in result["lines"]
        ]

        poeNinjaData.extend(items)

    for url in itemsUrl_list:
        qs = urlparse(url)
        ninjaType = amendSentence(parse_qs(qs.query)["type"][0]) + "s"

        r = requests.get(url)
        result = r.json()

        items = []

        for item in result["lines"]:
            name = ""
            if item["name"] != "":
                name = item["name"]
            else:
                name = item["baseType"]

            items.append(
                {
                    "baseType": name,
                    "detailsId": item["detailsId"],
                    "ninjaType": ninjaType,
                }
            )

        poeNinjaData.extend(items)

    with open("data.json", "w") as jsonfile:
        json.dump(poeNinjaData, jsonfile)


def charactersAndTabs(request):
    if request.method == "GET":

        if os.stat("data.json").st_size == 0:
            getAllData(request)

        characters_url = "https://www.pathofexile.com/character-window/get-characters?accountName=R33son"
        stashTabs_url = "https://www.pathofexile.com/character-window/get-stash-items?league=Standard&realm=pc&accountName=R33son&tabs=1"

        r_characters = requests.get(characters_url, headers=headers, cookies=cookies)
        r_stashTabs = requests.get(stashTabs_url, headers=headers, cookies=cookies)

        results_characters = r_characters.json()
        results_stashTabs = r_stashTabs.json()

        characters = [
            {
                "name": character["name"],
                "class": character["class"],
                "level": character["level"],
                "league": character["league"],
            }
            for character in results_characters
        ]

        stashTabs = [
            {"name": stashTab["n"], "index": stashTab["i"], "color": stashTab["colour"]}
            for stashTab in results_stashTabs["tabs"]
        ]

        context = {
            "characters": characters,
            "stashTabs": stashTabs,
            "title": "Select character",
        }

        return render(request, "user/detail.html", context)


def characterDetail(request):
    if request.is_ajax and request.method == "GET":

        if "character_name" in request.GET:

            url = f"https://www.pathofexile.com/character-window/get-items?accountName=R33son&character={request.GET['character_name']}"

            r = requests.get(url, headers=headers, cookies=cookies)

            results = r.json()

            items = []

            for item in results["items"]:
                if (
                    item["inventoryId"] != "Offhand2"
                    and item["inventoryId"] != "Weapon2"
                ):

                    if item["inventoryId"] == "Flask":
                        flask_id = str(item["x"] + 1)
                    else:
                        flask_id = ""

                    fracturedMods = item.get("fracturedMods")
                    utilityMods = item.get("utilityMods")
                    implicitMods = item.get("implicitMods")
                    explicitMods = item.get("explicitMods")
                    craftedMods = item.get("craftedMods")
                    enchantMods = item.get("enchantMods")
                    corrupted = item.get("corrupted")
                    name = item.get("name")
                    height = item.get("h")
                    stackSize = item.get("stackSize")

                    items.append(
                        {
                            "typeLine": item["typeLine"],
                            "icon": item["icon"],
                            "inventoryId": item["inventoryId"],
                            "flask": flask_id,
                            "fracturedMods": fracturedMods,
                            "utilityMods": utilityMods,
                            "implicitMods": implicitMods,
                            "explicitMods": explicitMods,
                            "craftedMods": craftedMods,
                            "enchantMods": enchantMods,
                            "corrupted": corrupted,
                            "name": name,
                            "frameType": item["frameType"],
                            "height": height,
                            "x": item["x"],
                            "y": item["y"],
                            "stackSize": stackSize,
                        }
                    )

            return JsonResponse({"character_items": items, "gridCells": []}, status=200)
        else:
            return JsonResponse({"message": "Character does not exists"}, status=400)


def stashTab(request):

    poeNinjaCurrency_baseUrl = f"https://poe.ninja/"

    if request.is_ajax and request.method == "GET":

        if "stashtab_index" in request.GET:

            url = f'https://www.pathofexile.com/character-window/get-stash-items?league=Standard&realm=pc&accountName=R33son&tabs=0&tabIndex={request.GET["stashtab_index"]}'
            r = requests.get(url, headers=headers, cookies=cookies)
            results = r.json()

            c = Counter()

            stash_items = []

            for item in results["items"]:
                stackSize = None
                if "stackSize" not in item:
                    c[item["typeLine"]] += 1
                    stackSize = c[item["typeLine"]]
                else:

user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="#">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'user/js/main.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/utilities.css' %}">
    
    <title>POE - {{ title }}</title>
</head>
<h2>POE - {{ title }}</h2>
<body id="bg" style="background-image: url('{% static "user/images/background.jpg" %}');">
    {% block content %}{% endblock content %}

    <script>
        
    </script>
</body>
</html>

user/templates/user/detail.html
{% extends "user/base.html" %}
{% block content %}
{% load mathfilters %}
<div class="mainLayout">

    {% csrf_token %} 
    <div class="charactersContainer window-bg">
        <h2 class="title m-0">CHARACTERS</h2>
        <div class="ic">
            <div class="scrollbar">
                {% for character in characters %}
                    <div class="characterWindow" value="{{ character.name }}">
                        <div class="icon {{ character.class }}"></div>
                        <div class="name pl-10 pt-5">{{ character.name }} </div>
                        <div class="level-class pl-10">Level {{ character.level }} {{ character.class }}</div>
                        <div class="league pl-10">{{ character.league }} League</div>  
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


    <div class="charatcerItemsContainer window-bg">
        <h2 class="title m-0">EQUIPEMENT</h2>
        <div class="ic">
            <!--Only for displaying Item slots-->
            <div class="itemSlotContainer">
                <div class="itemSlot itemHelm"></div>
                <div class="itemSlot itemWeapon"></div>
                <div class="itemSlot itemOffhand"></div>   
                <div class="itemSlot itemBodyArmour"></div>
                <div class="itemSlot itemRing"></div>
                <div class="itemSlot itemRing2"></div>
                <div class="itemSlot itemAmulet"></div>
                <div class="itemSlot itemGloves"></div>
                <div class="itemSlot itemBoots"></div>
                <div class="itemSlot itemBelt"></div>
                <div class="itemSlot itemTrinket"></div>
                <div class="itemSlot itemFlask1"></div>
                <div class="itemSlot itemFlask2"></div>
                <div class="itemSlot itemFlask3"></div>
                <div class="itemSlot itemFlask4"></div>
                <div class="itemSlot itemFlask5"></div>
            </div>
            <div class="equippedItemsContainer" id="equippedItemsContainer"></div>  
        </div>
    </div>

    <div class="mainInvetoryContainer window-bg">
        <h2 class="title m-0">INVENTORY</h2>
        <div class="inner ic">
            <div class="inventoryItems">
                <div class="grid"> <!--ONLY FOR DISPLAYING GRID LINES-->
                    {% for i in "x"|ljust:"60" %}
                        <div class="gridLines">{{x}}</div>
                    {% endfor %}
                </div>
                <div class="itemsToDisplay" id="itemsToDisplay"></div>
            </div>
        </div>
    
    
    </div>


    <div class="stashtabContainer window-bg">
        <h2 class="title m-0">STASH TABS</h2>
        <div class="inner ic">
            <div class="scrollbar">
                {% for stashTab in stashTabs  %}
                    <button class="stashbtn" value="{{ stashTab.index }}" style="background-color: rgb({{ stashTab.color.r }} {{ stashTab.color.g }} {{ stashTab.color.b }} /50%); border: rgb({{ stashTab.color.r|div:0.8 }}, {{ stashTab.color.g|div:0.8 }}, {{ stashTab.color.b|div:0.8 }}) 2px solid;">{{stashTab.name}}</button>
                    <div id="{{ stashTab.name }}" class="testcontainer stashTab" style="display:none"></div>  
                {% endfor %}
            </div>
            <div class="stashTabDetail">
                <div class="tags">
                    <div class="icon">
                        <h2>Icon</h3>
                    </div>
                    <div class="name">
                        <h2>Name</h2>
                    </div>
                    <div class="quantity">
                        <h2>Quantity</h2>
                    </div>
                </div>
                <div class="stashContent" id="stashContent"></div>
            </div>
        </div>
       
    </div>
</div>
{% endblock content %}

user/templates/user/user.html
{% extends 'user/base.html' %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
        <div class="custom-select" style="witdh: 200px;">
            <select name="character" id="id_character" required=''>
                {% for name in names %}

                    <option value="{{ name}}">{{ name }}</option>
                
                {% endfor %}
            </select>
            <input type="submit" value="OK"/>
        </div>
    </form>
{% endblock content %}
    